name: Godot CI

#When Workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #Workflow runs Manually from actions
  workflow_dispatch:

#What the workflow does
jobs:
  build:
    #Job Build:
    runs-on: ubuntu-latest

    #steps provide a sequence of tasks to be ran in the job.
    steps:
      - uses: actions/checkout@v3
      - name: run a script
        run: echo Testing ci setup.
      
