name: Godot CI Tests

# When Workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Workflow runs Manually from actions
  workflow_dispatch:

# What the workflow does
jobs:
  test:
    # Job Test:
    runs-on: ubuntu-latest

    steps:
      # Checks out this repository
      - uses: actions/checkout@v3

      # Download and setup Godot 4.3 headless explicitly
      #THIS BUILD WORKS.
      # Download standard Godot binary explicitly
      - name: Download Godot Headless
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          chmod +x Godot_v4.3-stable_linux.x86_64

      - name: Import Godot Resources (generate .godot folder with class_name support)
        run: |
          ./Godot_v4.3-stable_linux.x86_64 --headless --import --quit --path .

      - name: Run Unit Tests
        run: |
          ./Godot_v4.3-stable_linux.x86_64 --headless -s addons/gut/gut_cmdln.gd -gdir=tests -gexit

