name: Godot CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libfontconfig1 libx11-6

    - name: Download Godot 4.3 Standard Edition
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        unzip Godot_v4.3-stable_linux.x86_64.zip -d godot-4.3
        chmod +x godot-4.3/Godot_v4.3-stable_linux.x86_64

    - name: Verify Godot Installation
      run: ./godot-4.3/Godot_v4.3-stable_linux.x86_64 --version

    - name: Run GUT Tests (Command Line)
      run: |
        ./godot-4.3/Godot_v4.3-stable_linux.x86_64 --headless --path . --script addons/gut/gut_cmdln.gd -d res://tests/

    - name: Save Test Results
      if: always()
      run: mkdir -p test-results && mv tests/results.xml test-results/ || echo "No test results found."

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
