name: Godot CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Godot
      run: |
        sudo add-apt-repository -y ppa:godotengine/ppa
        sudo apt-get update
        sudo apt-get install -y godot

    - name: Verify Godot Installation
      run: godot --version

    - name: Run GUT Tests
      run: |
        godot --headless --fix-imports --path . --script addons/gut/gut_cmdln.gd -d res://tests/

    - name: Save Test Results
      if: always()
      run: mkdir -p test-results && mv tests/results.xml test-results/ || echo "No test results found."

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
