name: Godot CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run GUT Tests (Using Docker for Godot 4.3)
      run: |
        docker run --rm -v $(pwd):/workspace barichello/godot-ci:4.3 \
          godot --headless --path /workspace --script /workspace/addons/gut/gut_cmdln.gd -d res://tests/

    - name: Save Test Results
      if: always()
      run: mkdir -p test-results && mv tests/results.xml test-results/ || echo "No test results found."

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
