name: Godot CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot 4.3
      uses: manleydev/setup-godot@v1
      with:
        version: 4.3
        use-mono: false  # Set to true if your project uses C#.

    - name: Run GUT Tests (Using Installed Godot)
      run: |
        godot --headless --fix-imports --path . --script addons/gut/gut_cmdln.gd -d res://tests/

    - name: Save Test Results
      if: always()
      run: mkdir -p test-results && mv tests/results.xml test-results/ || echo "No test results found."

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
