name: Godot CI Tests

# When Workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Workflow runs Manually from actions
  workflow_dispatch:

# What the workflow does
jobs:
  test:
    # Job Test:
    runs-on: ubuntu-latest

    # Steps provide a sequence of tasks to be run in the job.
    steps:
      # Checks out this repository
      - uses: actions/checkout@v3

      # Setup Godot Engine
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 3.4-stable
          export-templates: true

      # Run Godot Unit Tests
      - name: Run Unit Tests
        run: |
          godot --headless -s addons/gut/gut_cmdln.gd -gdir=tests -gexit
