name: Godot CI Tests

# When Workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Workflow runs Manually from actions
  workflow_dispatch:

# What the workflow does
jobs:
  test:
    # Job Test:
    runs-on: ubuntu-latest

    steps:
      # Checks out this repository
      - uses: actions/checkout@v3

      # Download and setup Godot 4.3 headless explicitly
      - name: Download Godot Headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_headless.64.zip
          unzip Godot_v4.3-stable_linux_headless.64.zip
          chmod +x Godot_v4.3-stable_linux_headless.64

      # Run Godot Unit Tests
      - name: Run Unit Tests
        run: |
          ./Godot_v4.3-stable_linux.x86_64 --headless -s addons/gut/gut_cmdln.gd -gdir=tests -gexit
